cache:
  directories:
  - $HOME/.m2
language: java
jdk:
- oraclejdk8
script: ./build.sh
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
- $GPG_DIR/publish.sh
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: sKGUO/hJqv7OVSVVrgskndd3D1n5uThczQ9v5YlHqfCfn28Wg4wSZPujTlfj0eD7oqGg8WDlJybaJy9zuw9OBPQD3ofy+WB4JRNyqWNmhksntl9aAB2LnBPclCS7YNmLZ0w+ZIc9qHxdDjaek18a0wlelA/VTNKoGyzvf0Jk0AFaov7RDBkmUca6W6wDOyEiF7MnkDt5jix9VxQFEZ9ATyXzMYas0tM5NGkO25ifLuBPwo7XRUMKBz9xye/07JfmeOBsOLqTvWbr9r3QvPyH4JdhEJsoCYWWnSi6R+TwK1BHMC3mJbToV/qq74zgWMjDyO4QZJW+PmJJOj+RqRDY3Kh4R2jCBZAManxrLRkivUg5cNL2AEWLKNHQFCtr6ToP+Q0sM6DbHmmBjnMMGd/oU38P69BvTUOwml6/un9ZO3Da8nkPo67d5LDwkcRt/vyKCKfIakkbCCWR9cuEpq/HbTKtd/3wupNvjMjA8MuLPG9zbYQVMDTA8mXL14CS657EihI+XyH7FaZrWwmygXF+8GqyGYdBMrd/OT6ujgOtRoopB8QemQH9ca1B4iSc8DrY/YXkUPQRPZyBoCVtVRYkVlWmlXz8ZPuR5+LYn7r9kXShHZMEUrxTncLxz15N3jN+Uw4Rkv3QdR1dk3nhRXn0TZ2O1KZiCCjirWWoxe050PE=
